Add rocket pool adapter to v2
Popcorn-Limited/contracts pull request #117
Opened 2023-09-01 12:16 UTC by mayorcoded

2023-09-04 10:11 UTC, RedVeil commented on src/vault/v2/adapter/rocketpool/RocketPoolAdapter.sol
> +            return;
why do you return here?

2023-09-04 11:30 UTC, mayorcoded commented on src/vault/v2/adapter/rocketpool/RocketPoolAdapter.sol
> +            return;
Alright then. I'll make the change

2023-09-13 06:17 UTC, 0xruhum commented on src/vault/v2/adapter/rocketpool/IRocketpool.sol
> +}
I think we have these interfaces defined somewhere else already. We should reuse them.

2023-09-13 06:19 UTC, 0xruhum commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    IWETH public wETH; //0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
Wrapped ETH's short form is WETH

2023-09-13 06:20 UTC, 0xruhum commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    RocketDepositPoolInterface public rocketDepositPool;
These values are always the same. We should make them constant state variables to save gas costs on deployment and runtime.

There's no benefit in passing them in the initialize function. That way we can also remove validating the inputs

2023-09-13 06:24 UTC, 0xruhum commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +        rocketDepositPool.deposit{value: amount}(); //TODO: how do I know that it's open for deposit
Is there any benefit in checking whether we can deposit to ETH into rocket pool?

If it's disabled we can't really do anything anyways.

2023-09-13 06:28 UTC, 0xruhum commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    }
this assumes that rETH keeps its peg to ETH.

What would happen here if rETH loses its peg?
What if we can't burn through the rocket pool contracts and can't swap through uniswap? Is there a way we could allow users to withdraw rETH directly?

2023-09-13 06:29 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +        _depositUnderlying(totalAssets()); //this returns the balance of the adapter back to the protocol
Does this change work for all the other adapters as well?

2023-09-13 06:30 UTC, 0xruhum commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +//    );
why is this commented out?

2023-09-13 06:30 UTC, 0xruhum commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +    //assertApproxEqAbs(iouBalance(), oldIouBalance, _delta_, "iou balance");
why is this commented out?

2023-09-13 06:32 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +    }
doesn't seem to be used anywhere. The comment says that it MUST be overridden but the rocket pool doesn't.

What's this used for?

2023-09-13 06:34 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +    }
the rocket pool test contract creates the adapter in `verify_adapterInit`. The one created in this function is useless since the address is never returned. What's the point of this?

2023-09-13 06:34 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +            emit log("PING");
remove logs please

2023-09-13 06:34 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +            emit log("PING1");
s/a

2023-09-13 06:35 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +        //adapter.setPerformanceFee(performanceFee);
why's this commented out? If it's unnecessary, please remove it

2023-09-13 06:36 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +        //adapter.harvest();
how are we testing `harvest()` with the call to `harvest()` commented out?

2023-09-13 06:36 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +//        assertEq(lastHarvest, adapter.lastHarvest(), "should not auto harvest");
why's this commented out?

2023-09-13 06:36 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +//    }
s/a

2023-09-13 06:37 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +//    }
s/a

2023-09-13 06:37 UTC, 0xruhum commented on test/vault/v2/base/BaseAdapterTest.sol
> +}
s/a

2023-09-13 06:37 UTC, 0xruhum commented on test/vault/v2/base/interfaces/ITestConfigStorage.sol
> +}
we should already have this interface somewhere. Let's reuse it.

2023-09-13 09:50 UTC, mayowa-mentaport commented on src/vault/v2/adapter/rocketpool/IRocketpool.sol
> +}
Yea, it does, I just didn't think it was clean to reference an interface from the folder of another adapter because of the possible issues the dependency may cause. More so, it's a very small interface that I didn't think duplication was an issue.

2023-09-13 09:52 UTC, mayowa-mentaport commented
> PR needs some more work. The current state doesn't even compile.
> 
> I might have missed some of the stuff so we probably need to go over it again after the marked stuff is addressed.
> 
> I'd also like to have the CI stuff merged into the vaults-v2 branch so that compile & test issues are caught there.

@0xruhum The vault-v2 pr has been compiling since I added more adapters to it. Also, it compiles and runs tests in this current PR. Perhaps you'd have to double-check to ensure that all is okay in your local.

2023-09-13 10:07 UTC, mayowa-mentaport commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    RocketDepositPoolInterface public rocketDepositPool;
I think only `WETH` and `rocketStorage ` addresses remains the same, others are actually fetch from the rocket storage.

2023-09-13 10:07 UTC, mayowa-mentaport commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +        rocketDepositPool.deposit{value: amount}(); //TODO: how do I know that it's open for deposit
That's correct.

2023-09-13 10:10 UTC, mayowa-mentaport commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    }
I will look into this and revert

2023-09-13 10:12 UTC, mayowa-mentaport commented on src/vault/v2/base/BaseAdapter.sol
> +        _depositUnderlying(totalAssets()); //this returns the balance of the adapter back to the protocol
Yes, it does. `_withdraw` after pausing returns the underlying token to the contract. `_depositUnderlying` returns all underlying tokens in the contract back to the protocol. The signature change for `_deposit` was the reason for this change.

2023-09-13 10:17 UTC, mayowa-mentaport commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +//    );
The difference in the left and right value is quite greater than the `__delta__` which is 10 by default. So I wanted to get some comments on whether it can be changed. And also why the default is 10

2023-09-13 10:17 UTC, mayowa-mentaport commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +    //assertApproxEqAbs(iouBalance(), oldIouBalance, _delta_, "iou balance");
https://github.com/Popcorn-Limited/contracts/pull/117/files#r1324298382

2023-09-13 10:17 UTC, mayowa-mentaport commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +    //assertApproxEqAbs(iouBalance(), oldIouBalance, _delta_, "iou balance");
> The difference in the left and right value is quite greater than the `__delta__` which is 10 by default. So I wanted to get some comments on whether it can be changed. And also why the default is 10

2023-09-13 10:18 UTC, mayowa-mentaport commented on test/vault/v2/base/interfaces/ITestConfigStorage.sol
> +}
> Yea, it does, I just didn't think it was clean to reference an interface from the folder of another adapter because of the possible issues the dependency may cause. More so, it's a very small interface that I didn't think duplication was an issue.

2023-09-13 10:36 UTC, mayorcoded commented
> PR needs some more work. The current state doesn't even compile.
> 
> I might have missed some of the stuff so we probably need to go over it again after the marked stuff is addressed.
> 
> I'd also like to have the CI stuff merged into the vaults-v2 branch so that compile & test issues are caught there.

[@0xruhum](https://github.com/0xruhum) The vault-v2 pr has been compiling since I added more adapters to it. Also, it compiles and runs tests in this current PR. Perhaps you'd have to double-check to ensure that all is okay in your local.

2023-09-13 10:39 UTC, mayorcoded commented on src/vault/v2/adapter/rocketpool/IRocketpool.sol
> +}
Yea, it does, I just didn't think it was clean to reference an interface from the folder of another
adapter because of the possible issues the dependency may cause. More so, it's a very small
interface that I didn't think duplication was an issue.

2023-09-13 10:40 UTC, mayorcoded commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    RocketDepositPoolInterface public rocketDepositPool;
I think only `WETH` and `rocketStorage` addresses remains the same, others are actually fetch from
the rocket storage.

2023-09-13 10:41 UTC, mayorcoded commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +        rocketDepositPool.deposit{value: amount}(); //TODO: how do I know that it's open for deposit
I agree. Although reverting with a clear error message might be helpful for the user experience.

2023-09-13 10:43 UTC, mayorcoded commented on src/vault/v2/base/BaseAdapter.sol
> +        _depositUnderlying(totalAssets()); //this returns the balance of the adapter back to the protocol
Yes, it does. `_withdraw` after pausing returns the underlying token to the contract. `_depositUnderlying` returns all underlying tokens in the contract back to the protocol. The signature change for _deposit was the reason for this change.

2023-09-13 10:47 UTC, mayorcoded commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +//    );
The difference in the left and right value is quite greater than the `__delta__`  which is 10 by default.
So I wanted to get some comments on whether it can be changed. And also why the default is 10

2023-09-13 10:47 UTC, mayorcoded commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +    //assertApproxEqAbs(iouBalance(), oldIouBalance, _delta_, "iou balance");
> The difference in the left and right value is quite greater than the `__delta__` which is 10 by default. So I wanted to get some comments on whether it can be changed. And also why the default is 10

2023-09-13 10:48 UTC, mayorcoded commented on test/vault/v2/base/interfaces/ITestConfigStorage.sol
> +}
> Yea, it does, I just didn't think it was clean to reference an interface from the folder of another adapter because of the possible issues the dependency may cause. More so, it's a very small interface that I didn't think duplication was an issue.

2023-09-13 10:49 UTC, mayorcoded commented on test/vault/v2/base/BaseAdapterTest.sol
> +    }
I have added it, I must have skipped it. It's used to reset the setup of the tests if there's more than one config for the test.

2023-09-13 11:03 UTC, mayorcoded commented on test/vault/v2/base/BaseAdapterTest.sol
> +    }
I guess it's not necessary anymore. But it's used to create a clone separate from the original implementation.

2023-09-13 11:55 UTC, mayorcoded commented on test/vault/v2/base/BaseAdapterTest.sol
> +        //adapter.setPerformanceFee(performanceFee);
This test is specifically for strategies that have the harvest function and lined of code it was imported from the v1 adapter test

2023-09-13 12:14 UTC, mayorcoded commented on test/vault/v2/base/BaseAdapterTest.sol
> +        //adapter.setPerformanceFee(performanceFee);
This has been resolved

2023-09-13 12:14 UTC, mayorcoded commented on test/vault/v2/base/BaseAdapterTest.sol
> +        //adapter.harvest();
this has been reoslved

2023-09-13 12:14 UTC, mayorcoded commented on test/vault/v2/base/BaseAdapterTest.sol
> +//        assertEq(lastHarvest, adapter.lastHarvest(), "should not auto harvest");
This has been resolved

2023-09-13 13:05 UTC, 0xruhum commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    RocketDepositPoolInterface public rocketDepositPool;
Ok, I read through the rocket pool docs real quick: https://docs.rocketpool.net/developers/usage/contracts/contracts.html#interacting-with-rocket-pool

You're supposed to read *all* rocket pool contracts through the storage contract. So, `rocketStorage` can be constant here while you cannot store `rocketTokenRETH` and `rocketDepositPool` in a state variable. Those addresses can change at any time. Instead, store the keccak256 hash to retrieve those addresses in a constant variable and implement helper functions to fetch those addresses at runtime.

2023-09-13 13:06 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +        _depositUnderlying(totalAssets()); //this returns the balance of the adapter back to the protocol
then we should remove the commented out `_deposit()`call

2023-09-13 13:08 UTC, 0xruhum commented
works for me as well now 👍

2023-09-13 13:45 UTC, mayorcoded commented on src/vault/v2/base/BaseAdapter.sol
> +        _depositUnderlying(totalAssets()); //this returns the balance of the adapter back to the protocol
yeah, I left it in to draw attention to it. removing now

2023-09-13 13:53 UTC, mayorcoded commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    RocketDepositPoolInterface public rocketDepositPool;
Alright, this sounds neater.

2023-09-14 06:43 UTC, mayorcoded commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +//    );
Figured out that the `_delta_` here was the rocket pool deposit fee.

2023-09-14 06:43 UTC, mayorcoded commented on test/vault/v2/adapter/rocketpool/RocketpoolDepositor.t.sol
> +    //assertApproxEqAbs(iouBalance(), oldIouBalance, _delta_, "iou balance");
Figured out that the _delta_ here was the rocket pool deposit fee.

2023-09-14 12:26 UTC, mayorcoded commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    }
we can always check the amount out from the swap covers the withdrawal amount from the sender, but that can only happen within `_withdrawUnderlying` function. This would also mean that `underlying.safeTransfer(receiver, amount);` would sometimes error out cuz there's no return from the  `_withdrawUnderlying` function.

2023-09-14 14:00 UTC, 0xruhum requested changes

2023-09-15 10:44 UTC, 0xruhum commented on src/vault/v2/adapter/rocketpool/RocketpoolAdapter.sol
> +    }
Saving the variable in memory is just wasting gas

```sol
    function _getDepositPool() internal view returns(RocketDepositPoolInterface) {
        return RocketDepositPoolInterface(rocketStorage.getAddress(rocketDepositPoolKey));
    }
    
    function _getRocketToken() internal view returns(RocketTokenRETHInterface) {
        return RocketTokenRETHInterface(rocketStorage.getAddress(rocketTokenRETHKey));
    }
```

2023-09-18 08:20 UTC, merged