Refactor Vault Controller
Popcorn-Limited/contracts pull request #125
Opened 2023-10-04 12:47 UTC by mayorcoded

2023-10-04 16:36 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +        uint256 initialDeposit
unused parameter

2023-10-04 20:15 UTC, 0xruhum commented
I've removed some of the remaining unused logic and rebased the branch on the one I've used for the TemplateRegistry. I think we can stick to using this one for the remaining work that needs to be done. Since everything is so tightly coupled, it's difficult to separate PRs cleanly. I haven't touched any of the tests yet. Will get started with that in the morning.

2023-10-04 20:18 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +        (bool success, ) = IVault(vault).initialize(vaultData, strategy);
Any future version of a vault has to stick to the current initialize interface (including the `BaseVaultConfig` struct) to be compatible with this factory contract. I think using separate factory contracts for each major version is the way to go here. The same Template & Vault Registry can be used for all of them. @RedVeil

2023-10-05 06:07 UTC, mayorcoded commented
> Looks good. But, the tests have to be adjusted. In `VaultController.t.sol` there are tests that use `deployAdapter()`, `setPerformanceFee()`, etc. All of that stuff isn't part of the VaultFactory contract anymore.

Yeah, I am still working on the tests. I just opened a draft pr to show the progress on the task

2023-10-05 12:00 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +contract VaultFactory is Owned {
I think we can remove the Owned contract here. There's no function that needs to be protected.

2023-10-08 06:20 UTC, 0xruhum requested changes

2023-10-08 06:20 UTC, 0xruhum commented on src/vault/TemplateRegistry.sol
> +    return allTemplates[version][category][0];
For the strategy category you'd always return the first strategy that was registered. What do you want to use that for?

2023-10-08 06:20 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +    function setVaultRegistry(address newVaultRegistry) external onlyOwner {
I don't see a scenario where we'd update the registry without also updating the factory contract.

2023-10-08 06:20 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +        vaultRegistry.addFactory(address(this));
This wouldn't work because only the owner can add factories. And the owner is the AdminProxy

2023-10-08 06:20 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +    bytes32 public immutable SINGLE_STRATEGY_VAULT = "SingleStrategyVault";
We said that each vault type gets their own factory contract. We don't need this distinction here.

Instead, we should rename the file to SingleStrategyVaultFactory and only allow that vault type to be deployed

2023-10-08 06:20 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +    bytes32 public immutable REWARD_CLAIMER_STRATEGY = "RewardClaimerStrategy";
I don't like the idea of separating strategies by their type into different categories. There should only be single "STRATEGY" category

2023-10-08 06:20 UTC, 0xruhum commented on src/vault/VaultRegistry.sol
> +  /// @param _owner `VaultFactory`
The owner is the admin proxy.

2023-10-08 06:20 UTC, 0xruhum commented on test/vault/VaultFactory.t.sol
> +            registry: address (0),
formatting

2023-10-08 06:20 UTC, 0xruhum commented on test/vault/VaultFactory.t.sol
> +            protocolInitData: abi.encode()
you can just pass `""` instead of `abi.encode()`.

2023-10-08 07:36 UTC, 0xruhum commented on src/interfaces/vault/IVaultRegistry.sol
>    address creator;
I don't think we need to store this here. Waste of storage space. The same information can be pulled through the `vault` contract.

2023-10-09 08:46 UTC, 0xruhum commented on src/vault/VaultFactory.sol
> +    bytes32 public immutable SINGLE_STRATEGY_VAULT = "SingleStrategyVault";
fixed this

2023-10-11 07:01 UTC, 0xruhum commented
looks fine.

@RedVeil wanna look over this one last time before we merge it?

2023-10-11 14:23 UTC, merged