Lverage strategy poc
Popcorn-Limited/contracts pull request #134
Opened 2023-10-31 14:37 UTC by mayorcoded

2023-11-02 10:20 UTC, RedVeil commented on src/strategies/aave/AaveV3Leverage.sol
> +        for (uint256 i = 0; i < leverage; i++) {
I think this is way easier. 
1. calc ltv with the new deposit
2. check leverage ratio
3. calc how much we need to flashloan (taking new deposit into account)
4. flashloan
5. deposit all via lido etc.

2023-11-02 16:32 UTC, 0xruhum requested changes

2023-11-02 16:32 UTC, 0xruhum commented on src/adapter/aave/v3/AaveV3Adapter.sol
> +
should be moved into the `AaveV3Leverage` contract.

2023-11-02 16:32 UTC, 0xruhum commented on src/strategies/aave/AaveV3Leverage.sol
> +    IWETH public weth;
isn't initialized properly. Also, these addresses are known. Use constant values

2023-11-02 16:32 UTC, 0xruhum commented on src/strategies/aave/AaveV3Leverage.sol
> +        _onDeposit(amount, 10);
why 10? Use a constant state variable and give it a descriptive name so that it isn't a magic value

2023-11-02 16:32 UTC, 0xruhum commented on src/strategies/aave/AaveV3Leverage.sol
> +    ) external returns (bool) {
only allow AAVE to call this

2023-11-02 16:32 UTC, 0xruhum commented on src/strategies/aave/AaveV3Leverage.sol
> +        address initiator,
verify that the initiator is our contract

2023-11-06 15:32 UTC, 0xruhum requested changes
Can you add some tests to verify that it works as expected?

2023-11-06 15:32 UTC, 0xruhum commented on src/adapter/aave/v3/AaveV3Adapter.sol
> +    IPoolAddressProvider public constant poolAddressProvider = IPoolAddressProvider(0x7B4EB56E7CD4b454BA8ff71E4518426369a138a3);
we should move this into the leverage strat file as well. It's not used by the base adapter.

2023-11-06 15:32 UTC, 0xruhum commented on src/strategies/aave/AaveV3Leverage.sol
> +        _getFlashLoan(flashLoanAmount, leverage);
How does this work? You borrow first, then deposit, and then take a flashloan?

Why do we need a flashloan at all? Can't we just use a supply -> borrow -> supply loop?

2023-11-07 12:19 UTC, mayorcoded commented on src/strategies/aave/AaveV3Leverage.sol
> +        _getFlashLoan(flashLoanAmount, leverage);
The `supply -> borrow -> supply` loop was the initial design we had, but if you follow [this comment](https://github.com/Popcorn-Limited/contracts/pull/134#discussion_r1379886540) from @RedVeil, you'll see the logic spelt out...although it's still not totally felshed out, but the goal is to somehow avoid looping at all by taking a flashloan, but I also fail to understand how taking a flashloan provides the needed leverage given that we have to repay the loan. Let me know your input on this, on whether we should stick with the looping logic, or how else we could take advantage of flashloan in this instance. Once the idea is clear, I will update the implementation and add a test to verify the logic.

2024-06-13 11:58 UTC, closed without merging