Feat/curve gauge compounder
Popcorn-Limited/contracts pull request #149
Opened 2024-02-02 06:55 UTC by RedVeil

2024-02-03 07:43 UTC, 0xruhum requested changes

2024-02-03 07:43 UTC, 0xruhum commented on foundry.toml
> +evm_version = "shanghai"
any contract we compile in this repo and deploy to Arbitrum might break, because PUSH0 isn't supported on Arbitrum, see https://docs.arbitrum.io/for-devs/concepts/differences-between-arbitrum-ethereum/solidity-support

Need to update the configuration so that we run tests with `evm_version == shanghai` but compile & deploy with `evm_version == paris`.

2024-02-03 07:43 UTC, 0xruhum commented on src/vault/adapter/curve/gauge/mainnet/CurveGaugeCompounder.sol
> +    }
don't we normally wrap this in try/catch?

2024-02-06 03:47 UTC, RedVeil commented on src/vault/adapter/curve/gauge/mainnet/CurveGaugeCompounder.sol
> +    }
yeah true probably need to add a nested try catch here for both calls

2024-02-06 03:48 UTC, RedVeil commented on foundry.toml
> +evm_version = "shanghai"
is there a way to switch profiles test by test? so we can test arbitrum on a different `evm_version`?

2024-02-06 05:49 UTC, 0xruhum commented on foundry.toml
> +evm_version = "shanghai"
Can select specific profiles through the `FOUNDRY_PROFILE` env variable: https://book.getfoundry.sh/reference/config/overview?highlight=profile#profiles

one solution would be to use a MAKEFILE where we select specific foundry profiles for given commands, e.g. `make test` will set `FOUNDRY_PROFILE` to `profile.test` where `evm_version = shanghai`.

2024-02-12 09:03 UTC, merged