Feat/enso strats
Popcorn-Limited/contracts pull request #173
Opened 2024-06-10 14:09 UTC by RedVeil

2024-06-12 13:53 UTC, 0xruhum requested changes

2024-06-12 13:53 UTC, 0xruhum commented on src/peripheral/oracles/MainOracle.sol.txt
> +// SPDX-License-Identifier: GPL-3.0
why is this a `.txt` file?

2024-06-12 13:53 UTC, 0xruhum commented on src/peripheral/oracles/adapter/AaveV3Oracle.sol
> +    /// @return The converted amount.
docs should be updated.

We should add a small note that aTokens in v3 are 1:1 with the underlying token to explain why we just return `inAmount`.

2024-06-12 13:53 UTC, 0xruhum commented on src/peripheral/oracles/adapter/PendleLpOracle.sol
> +    uint32 internal constant MIN_TWAP_WINDOW = 5 minutes;
why 5 minutes? Can we link to docs or something like that where they recommend to use 5 minutes?

2024-06-12 13:53 UTC, 0xruhum commented on src/strategies/EnsoConverter.sol
> +        uint256 ta = this.totalAssets();
why don't we just call `_totalAssets()`?

2024-06-12 13:53 UTC, 0xruhum commented on test/Tester.t.sol
>      function testA() public {
first time seeing this contract. What's it supposed to test?

2024-06-12 13:53 UTC, 0xruhum commented on test/strategies/enso/EnsoAaveDepositor.t.sol
> +        );
why not use `console.log()`? 
https://book.getfoundry.sh/reference/forge-std/console-log

2024-06-14 12:08 UTC, RedVeil commented on src/strategies/EnsoConverter.sol
> +        uint256 ta = this.totalAssets();
cause it needs to include asset bal + _totalAssets

2024-06-14 12:08 UTC, RedVeil commented on src/peripheral/oracles/adapter/PendleLpOracle.sol
> +    uint32 internal constant MIN_TWAP_WINDOW = 5 minutes;
Honestly i just took the data here from enso-price-oracle which they use for uniV3 oracle

2024-06-14 13:21 UTC, 0xruhum commented on src/strategies/EnsoConverter.sol
> +        uint256 ta = this.totalAssets();
yeah but `this.totalAssets()` essentially means we make an external call from contract A to contract A. Really unnecessary gas overhead. There should be some way we can move the logic to an internal function that we just call instead of having to call an `external` function

2024-12-19 12:06 UTC, closed without merging