Vaults V2 draft
Popcorn-Limited/contracts pull request #89
Opened 2023-08-08 09:12 UTC by RedVeil

tests are not working. That's left-over from v2.0. Also a lot of placeholder code and unfinished functions.

Opening up this draft PR so we have a place for discussions if necessary.

TODOs:
- [ ] add full test suite
    - [ ] fuzz tests for deposit & withdrawal
    - [ ] changing strategies while user funds are deposited
    - [ ] one of the strategies loses funds
- [ ] NatSpec comments
- [ ] base contracts / interfaces

2023-08-08 13:00 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +        useLpToken ? _depositLP(amount) : _depositUnderlying(amount);
I don't think this is a good idea. You add unnecessary complexity by allowing the asset of the vault and adapter to be different.

If we need to deposit an LP token, it should be acquired using the underlying asset **before** it's deposited into the vault

2023-08-08 13:00 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +    function rewardToken() external view virtual returns (address[] memory) {}
naming:

`rewardToken` sounds like a single token but the function returns a list

2023-08-08 13:15 UTC, RedVeil commented on src/vault/v2/base/BaseAdapter.sol
> +        useLpToken ? _depositLP(amount) : _depositUnderlying(amount);
The idea here was to create only one adapter per protocol that allows a metaAdapter and a normal adapter without needing two write two separate contracts.

2023-08-08 13:20 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +        useLpToken ? _depositLP(amount) : _depositUnderlying(amount);
should just be a normal adapter and we handle the meta stuff outside the vault, IMO. 

Otherwise, you have to compute `totalAssets()` differently depending on what token you have. That's a lot of if-else statements with additional gas costs both for deployment and runtime

2023-08-09 13:52 UTC, 0xruhum requested changes
Looked through the base contracts mostly. Some of the choices I disagree with.

2023-08-09 13:52 UTC, 0xruhum commented on src/vault/v2/base/BaseCompounder.sol
> +        IBaseAdapter(address(this))._claimRewards();
I'm still not a fan of creating a dependency between Adapters & Strategies.

They shouldn't interact with each other. Let the top-level contract handle it instead.

2023-08-09 13:52 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +    function maxDeposit() public view virtual returns (uint256) {
unneccessary, imo. Just throw if paused

2023-08-09 13:52 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +    function pause() external onlyOwner {
Ah, I really don't like adding admin stuff to the strategy. Ideally, the vault would just be paused by the vault owner. With X:1 vault:strategy ratio, we have the issue that pausing all the vaults isn't feasible.

Multiple vaults for 1 strategy is beneficial for harvesting but comes with big costs:
- need to keep track of whitelisted vaults
- admin privileges for adapter
- reward kickback becomes complicated. With 1:1 we wouldn't need to add the staking reward stuff to the strategy.

I don't think it's worth it.

2023-08-09 14:57 UTC, RedVeil commented on src/vault/v2/base/BaseAdapter.sol
> +    function maxWithdraw() public view virtual returns (uint256) {
Its there to be overriden in case the protocol actually has some limitations

2023-08-09 14:57 UTC, RedVeil commented on src/vault/v2/base/BaseAdapter.sol
> +    function maxDeposit() public view virtual returns (uint256) {
Its there to be overriden in case the protocol actually has some limitations

2023-08-09 14:58 UTC, RedVeil commented on src/vault/v2/base/BaseAdapter.sol
> +        if (!paused() && IBaseStrategy(address(this)).autoHarvest())
Is that really how it works? i thought it would just need this to find the signature. Since its only an internal state variable it would just cost gas for an SLOAD.

2023-08-09 15:01 UTC, RedVeil commented on src/vault/v2/base/BaseStrategy.sol
> +    function harvest(bytes memory optionalData) external virtual {
Dont know yet. Potentially there might be some compounder that use dynamic data from 0x and can only be called by permissioned actors. I thought its better to have it there than to need it later. in 99% of cases it will simply be empty and unused. But if we dont add these things now its so much harder to change later

2023-08-09 15:04 UTC, RedVeil commented on src/vault/v2/base/BaseCompounder.sol
> +        IBaseAdapter(address(this))._claimRewards();
On the autoharvest stuff i can see it. My thought there was that 3 vaults could harvest and one doesnt. Making them an effective free rider. So it might make more sense to have it here. But it makes them more coupled.

2023-08-09 15:06 UTC, 0xruhum commented on src/vault/v2/base/BaseCompounder.sol
> +        IBaseAdapter(address(this))._claimRewards();
This doesn't really prevent one from being a freeloader either. The vault with more frequent deposits/withdrawals will be the one taking most of the burden.

2023-08-09 15:07 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +    function maxDeposit() public view virtual returns (uint256) {
We never enforce the limitation tho. It doesn't check whether the given amount in `deposit()` surpasses `maxDeposit()`. Just letting it throw would be more gas efficient for the happy case.

Is there a protocol where we expect to use it?

2023-08-09 15:12 UTC, 0xruhum commented on src/vault/v2/base/BaseAdapter.sol
> +        if (!paused() && IBaseStrategy(address(this)).autoHarvest())
Just tested it with a dead simple project. Foundry shows it as an external call in the trace. But, it only increases gas costs by 492. I'm not sure how that would scale for more complex functions.

2023-08-10 06:20 UTC, 0xruhum commented on src/vault/v2/base/BaseCompounder.sol
> +        IBaseAdapter(address(this))._claimRewards();
> For claimRewards here i wanted to reduce the amount of code a dev has to write in the toplevel. Its just duplicate, adds a mental overhead that the dev needs to keep in mind and the reviewer aswell. So i feel like its a good idea if you only need to write minimal amounts of code to add new strategies or adapter.

I get that but the current inheritance structure doesn't really allow that.

2023-08-10 13:46 UTC, 0xruhum commented on src/vault/v2/base/BaseStrategy.sol
> +        _accrueVaultReward(msg.sender);
same thing has to be done on every deposit from a vault. Since the vault's balance has an effect on the rewards they earn

2023-08-10 13:46 UTC, 0xruhum commented on src/vault/v2/base/BaseStrategy.sol
> +            uint256(10 ** decimals()),
where do we get the decimals from? Where's the function implemented?

2023-08-10 13:46 UTC, 0xruhum commented on src/vault/v2/base/BaseStrategy.sol
> +                uint256(10 ** decimals()),
where do we get the decimals from? Where's the function defined?

2023-08-10 13:46 UTC, 0xruhum commented on src/vault/v2/base/BaseStrategy.sol
> +                totalAssetDeposited(),
Where's the function defined? A strategy doesn't really know the total deposit amount. Only the adapter would know about it.

2023-08-10 13:46 UTC, 0xruhum commented on src/vault/v2/base/BaseStrategy.sol
> +        uint256 vaultShares = balanceOf[vault];
unused variable

2023-08-10 13:46 UTC, 0xruhum commented on src/vault/v2/base/BaseStrategy.sol
> +            token.transfer(msg.sender, vaultReward);
we should use SafeERC20 here.

2023-08-11 13:28 UTC, 0xruhum commented on src/vault/v2/base/BaseRewardClaimer.sol
> +        uint totalAssetDeposited = totalAssets();
A strategy doesn't have a `totalAssets()` function. Only the adapter does.

A adapter handles the deposits and withdrawals of `asset`. A strategy **only** handles the reward tokens that we receive from using a protocol through an adapter.

2023-08-17 08:10 UTC, merged